#!/usr/bin/env python3
"""Regenerate owned archive fixtures. Runtime tests need no archive programs."""
from __future__ import annotations

import argparse
import binascii
from io import BytesIO
from pathlib import Path
import shutil
import subprocess
import tempfile
import zipfile


def image(tag: int) -> bytes:
    header = bytearray(b"NES\x1a" + bytes(12))
    header[4:7] = bytes((1, 1, 2))
    program = bytearray([0xEA]) * 0x4000
    program[:7] = bytes((0xA9, tag, 0x85, 0, 0x4C, 4, 0x80))
    for offset in (0x3FFA, 0x3FFC, 0x3FFE):
        program[offset:offset + 2] = b"\x00\x80"
    return bytes(header + program + bytearray(0x2000))


def zip_fixture(entries: list[tuple[str, bytes]], method: int = zipfile.ZIP_DEFLATED) -> bytes:
    buffer = BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=method, compresslevel=9) as archive:
        for name, data in entries:
            info = zipfile.ZipInfo(name, date_time=(2000, 1, 1, 0, 0, 0))
            info.compress_type = method
            info.external_attr = 0o100644 << 16
            archive.writestr(info, data)
    return buffer.getvalue()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seven-zip", default=shutil.which("7zz") or shutil.which("7z"))
    args = parser.parse_args()
    if not args.seven_zip:
        raise SystemExit("7z or 7zz is needed only to regenerate the fixtures")
    root = Path(__file__).resolve().parent.parent
    build = root / "build"
    build.mkdir(exist_ok=True)
    first, second = image(0x11), image(0x22)
    member = "café/ゲーム😀.nes"
    fixtures = {
        "zip_single": zip_fixture([(member, first)]),
        "zip_multiple": zip_fixture([(member, first), ("second/game.nes", second), ("readme.txt", b"Owned test images\n")]),
        "zip_traversal": zip_fixture([("../outside.nes", first)]),
        "zip_absolute": zip_fixture([("/outside.nes", first)]),
        "zip_duplicate": zip_fixture([("folder\\game.nes", first), ("folder/game.nes", second)]),
        "zip_no_image": zip_fixture([("readme.txt", b"No game image\n")]),
        "zip_unsupported": zip_fixture([("game.nes", first)], zipfile.ZIP_BZIP2),
    }
    # TemporaryDirectory is confined to this repository's ignored build tree.
    with tempfile.TemporaryDirectory(prefix="media-fixtures-", dir=build) as temporary:
        workspace = Path(temporary).resolve()
        workspace.relative_to(build.resolve())
        unicode_path = workspace / member
        unicode_path.parent.mkdir(parents=True)
        unicode_path.write_bytes(first)
        (workspace / "game.nes").write_bytes(second)
        for name, files, extra in [
            ("seven_single", [member], ["-m0=LZMA"]),
            ("seven_solid", [member, "game.nes"], ["-m0=LZMA2", "-ms=on"]),
            ("seven_encrypted", [member], ["-m0=LZMA2", "-pfixture-password", "-mhe=on"]),
        ]:
            destination = workspace / (name + ".7z")
            command = [args.seven_zip, "a", "-t7z", "-mx=9", "-mtc=off", "-mta=off", "-mtm=off", "-bd", "-y", *extra, str(destination), *files]
            completed = subprocess.run(command, cwd=workspace, capture_output=True, check=False)
            if completed.returncode:
                raise RuntimeError(completed.stdout.decode(errors="replace") + completed.stderr.decode(errors="replace"))
            fixtures[name] = destination.read_bytes()

    output = [
        "/*", " * media_fixtures.h - Owned synthetic archive images", " *",
        " * Author: @frankischilling", " *",
        " * Generated by scripts/generate-media-fixtures.py.",
        " * Distributed under GNU GPL version 3 or any later version.",
        " * SPDX-License-Identifier: GPL-3.0-or-later", " */",
        "#ifndef CUPID_MEDIA_FIXTURES_H", "#define CUPID_MEDIA_FIXTURES_H", "#include <stdint.h>", "",
        f"#define MEDIA_FIXTURE_FIRST_CRC UINT32_C(0x{binascii.crc32(first):08x})",
        f"#define MEDIA_FIXTURE_SECOND_CRC UINT32_C(0x{binascii.crc32(second):08x})", "",
    ]
    for name, data in fixtures.items():
        output.append(f"static const uint8_t media_fixture_{name}[] = {{")
        for offset in range(0, len(data), 16):
            output.append("    " + ",".join(f"0x{value:02x}" for value in data[offset:offset + 16]) + ",")
        output.extend(["};", ""])
        print(f"{name}: {len(data)} bytes")
    output.append("#endif")
    destination = root / "src" / "tests" / "media_fixtures.h"
    destination.write_text("\n".join(output) + "\n", encoding="utf-8", newline="\n")
    print(destination)


if __name__ == "__main__":
    main()
